In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import  train_test_split


In [3]:
ffire=pd.read_csv('C:\\Users\\Janu&Vaibh\\Desktop\\HDSfoundation\\Datasets\\forestfires.csv')

In [4]:
forestfires=pd.DataFrame(ffire)

In [5]:
forestfires

X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
5    8  6   aug  sun  92.3   85.3  488.0  14.7  22.2  29   5.4   0.0   0.00
6    8  6   aug  mon  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0   0.00
7    8  6   aug  mon  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0   0.00
8    8  6   sep  tue  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0   0.00
9    7  5   sep  sat  92.5   88.0  698.6   7.1  22.8  40   4.0   0.0   0.00
10   7  5   sep  sat  92.5   88.0  698.6   7.1  17.8  51   7.2   0.0   0.00
11   7  5   sep  sat  92.8   73.2  713.0  22.6  19.3  38   4.0   0.0   0.00
12   6  5   aug  fri  63.5   70.8  665.3   0.8  17.0  72   6.7   0.0   0.00
13   6  5   sep  mon  90.9  126.5  686.5   7.0  21.3  42   2.2   0.0   0.00
14   6  5   sep  wed  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0   0.00
15   6  5   sep  fri  93.3  141.2  713.9  13.9  22.9  44   5.4   0.0   0.00
16   5  5   mar  sat  91.7   35.8   80.8   7.8  15.1  27   5.4   0.0   0.00
17   8  5   oct  mon  84.9   32.8  664.2   3.0  16.7  47   4.9   0.0   0.00
18   6  4   mar  wed  89.2   27.9   70.8   6.3  15.9  35   4.0   0.0   0.00
19   6  4   apr  sat  86.3   27.4   97.1   5.1   9.3  44   4.5   0.0   0.00
20   6  4   sep  tue  91.0  129.5  692.6   7.0  18.3  40   2.7   0.0   0.00
21   5  4   sep  mon  91.8   78.5  724.3   9.2  19.1  38   2.7   0.0   0.00
22   7  4   jun  sun  94.3   96.3  200.0  56.1  21.0  44   4.5   0.0   0.00
23   7  4   aug  sat  90.2  110.9  537.4   6.2  19.5  43   5.8   0.0   0.00
24   7  4   aug  sat  93.5  139.4  594.2  20.3  23.7  32   5.8   0.0   0.00
25   7  4   aug  sun  91.4  142.4  601.4  10.6  16.3  60   5.4   0.0   0.00
26   7  4   sep  fri  92.4  117.9  668.0  12.2  19.0  34   5.8   0.0   0.00
27   7  4   sep  mon  90.9  126.5  686.5   7.0  19.4  48   1.3   0.0   0.00
28   6  3   sep  sat  93.4  145.4  721.4   8.1  30.2  24   2.7   0.0   0.00
29   6  3   sep  sun  93.5  149.3  728.6   8.1  22.8  39   3.6   0.0   0.00
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
487  5  4   aug  tue  95.1  141.3  605.8  17.7  26.4  34   3.6   0.0  16.40
488  4  4   aug  tue  95.1  141.3  605.8  17.7  19.4  71   7.6   0.0  46.70
489  4  4   aug  wed  95.1  141.3  605.8  17.7  20.6  58   1.3   0.0   0.00
490  4  4   aug  wed  95.1  141.3  605.8  17.7  28.7  33   4.0   0.0   0.00
491  4  4   aug  thu  95.8  152.0  624.1  13.8  32.4  21   4.5   0.0   0.00
492  1  3   aug  fri  95.9  158.0  633.6  11.3  32.4  27   2.2   0.0   0.00
493  1  3   aug  fri  95.9  158.0  633.6  11.3  27.5  29   4.5   0.0  43.32
494  6  6   aug  sat  96.0  164.0  643.0  14.0  30.8  30   4.9   0.0   8.59
495  6  6   aug  mon  96.2  175.5  661.8  16.8  23.9  42   2.2   0.0   0.00
496  4  5   aug  mon  96.2  175.5  661.8  16.8  32.6  26   3.1   0.0   2.77
497  3  4   aug  tue  96.1  181.1  671.2  14.3  32.3  27   2.2   0.0  14.68
498  6  5   aug  tue  96.1  181.1  671.2  14.3  33.3  26   2.7   0.0  40.54
499  7  5   aug  tue  96.1  181.1  671.2  14.3  27.3  63   4.9   6.4  10.82
500  8  6   aug  tue  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8   0.00
501  7  5   aug  tue  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8   0.00
502  4  4   aug  tue  96.1  181.1  671.2  14.3  20.7  69   4.9   0.4   0.00
503  2  4   aug  wed  94.5  139.4  689.1  20.0  29.2  30   4.9   0.0   1.95
504  4  3   aug  wed  94.5  139.4  689.1  20.0  28.9  29   4.9   0.0  49.59
505  1  2   aug  thu  91.0  163.2  744.4  10.1  26.7  35   1.8   0.0   5.80
506  1  2   aug  fri  91.0  166.9  752.6   7.1  18.5  73   8.5   0.0   0.00
507  2  4   aug  fri  91.0  166.9  752.6   7.1  25.9 

In [6]:
features=pd.DataFrame(forestfires,columns=['temp','RH','wind','rain'])
features

temp  RH  wind  rain
0     8.2  51   6.7   0.0
1    18.0  33   0.9   0.0
2    14.6  33   1.3   0.0
3     8.3  97   4.0   0.2
4    11.4  99   1.8   0.0
5    22.2  29   5.4   0.0
6    24.1  27   3.1   0.0
7     8.0  86   2.2   0.0
8    13.1  63   5.4   0.0
9    22.8  40   4.0   0.0
10   17.8  51   7.2   0.0
11   19.3  38   4.0   0.0
12   17.0  72   6.7   0.0
13   21.3  42   2.2   0.0
14   26.4  21   4.5   0.0
15   22.9  44   5.4   0.0
16   15.1  27   5.4   0.0
17   16.7  47   4.9   0.0
18   15.9  35   4.0   0.0
19    9.3  44   4.5   0.0
20   18.3  40   2.7   0.0
21   19.1  38   2.7   0.0
22   21.0  44   4.5   0.0
23   19.5  43   5.8   0.0
24   23.7  32   5.8   0.0
25   16.3  60   5.4   0.0
26   19.0  34   5.8   0.0
27   19.4  48   1.3   0.0
28   30.2  24   2.7   0.0
29   22.8  39   3.6   0.0
..    ...  ..   ...   ...
487  26.4  34   3.6   0.0
488  19.4  71   7.6   0.0
489  20.6  58   1.3   0.0
490  28.7  33   4.0   0.0
491  32.4  21   4.5   0.0
492  32.4  27   2.2   0.0
493  27.5  29   4.5   0.0
494  30.8  30   4.9   0.0
495  23.9  42   2.2   0.0
496  32.6  26   3.1   0.0
497  32.3  27   2.2   0.0
498  33.3  26   2.7   0.0
499  27.3  63   4.9   6.4
500  21.6  65   4.9   0.8
501  21.6  65   4.9   0.8
502  20.7  69   4.9   0.4
503  29.2  30   4.9   0.0
504  28.9  29   4.9   0.0
505  26.7  35   1.8   0.0
506  18.5  73   8.5   0.0
507  25.9  41   3.6   0.0
508  25.9  41   3.6   0.0
509  21.1  71   7.6   1.4
510  18.2  62   5.4   0.0
511  27.8  35   2.7   0.0
512  27.8  32   2.7   0.0
513  21.9  71   5.8   0.0
514  21.2  70   6.7   0.0
515  25.6  42   4.0   0.0
516  11.8  31   4.5   0.0

[517 rows x 4 columns]

In [7]:
target=pd.DataFrame(forestfires,columns=["area"])#features and target are in different dataframes
target

area
0     0.00
1     0.00
2     0.00
3     0.00
4     0.00
5     0.00
6     0.00
7     0.00
8     0.00
9     0.00
10    0.00
11    0.00
12    0.00
13    0.00
14    0.00
15    0.00
16    0.00
17    0.00
18    0.00
19    0.00
20    0.00
21    0.00
22    0.00
23    0.00
24    0.00
25    0.00
26    0.00
27    0.00
28    0.00
29    0.00
..     ...
487  16.40
488  46.70
489   0.00
490   0.00
491   0.00
492   0.00
493  43.32
494   8.59
495   0.00
496   2.77
497  14.68
498  40.54
499  10.82
500   0.00
501   0.00
502   0.00
503   1.95
504  49.59
505   5.80
506   0.00
507   0.00
508   0.00
509   2.17
510   0.43
511   0.00
512   6.44
513  54.29
514  11.16
515   0.00
516   0.00

[517 rows x 1 columns]

In [8]:
df=pd.concat([features,target],axis=1)
df

temp  RH  wind  rain   area
0     8.2  51   6.7   0.0   0.00
1    18.0  33   0.9   0.0   0.00
2    14.6  33   1.3   0.0   0.00
3     8.3  97   4.0   0.2   0.00
4    11.4  99   1.8   0.0   0.00
5    22.2  29   5.4   0.0   0.00
6    24.1  27   3.1   0.0   0.00
7     8.0  86   2.2   0.0   0.00
8    13.1  63   5.4   0.0   0.00
9    22.8  40   4.0   0.0   0.00
10   17.8  51   7.2   0.0   0.00
11   19.3  38   4.0   0.0   0.00
12   17.0  72   6.7   0.0   0.00
13   21.3  42   2.2   0.0   0.00
14   26.4  21   4.5   0.0   0.00
15   22.9  44   5.4   0.0   0.00
16   15.1  27   5.4   0.0   0.00
17   16.7  47   4.9   0.0   0.00
18   15.9  35   4.0   0.0   0.00
19    9.3  44   4.5   0.0   0.00
20   18.3  40   2.7   0.0   0.00
21   19.1  38   2.7   0.0   0.00
22   21.0  44   4.5   0.0   0.00
23   19.5  43   5.8   0.0   0.00
24   23.7  32   5.8   0.0   0.00
25   16.3  60   5.4   0.0   0.00
26   19.0  34   5.8   0.0   0.00
27   19.4  48   1.3   0.0   0.00
28   30.2  24   2.7   0.0   0.00
29   22.8  39   3.6   0.0   0.00
..    ...  ..   ...   ...    ...
487  26.4  34   3.6   0.0  16.40
488  19.4  71   7.6   0.0  46.70
489  20.6  58   1.3   0.0   0.00
490  28.7  33   4.0   0.0   0.00
491  32.4  21   4.5   0.0   0.00
492  32.4  27   2.2   0.0   0.00
493  27.5  29   4.5   0.0  43.32
494  30.8  30   4.9   0.0   8.59
495  23.9  42   2.2   0.0   0.00
496  32.6  26   3.1   0.0   2.77
497  32.3  27   2.2   0.0  14.68
498  33.3  26   2.7   0.0  40.54
499  27.3  63   4.9   6.4  10.82
500  21.6  65   4.9   0.8   0.00
501  21.6  65   4.9   0.8   0.00
502  20.7  69   4.9   0.4   0.00
503  29.2  30   4.9   0.0   1.95
504  28.9  29   4.9   0.0  49.59
505  26.7  35   1.8   0.0   5.80
506  18.5  73   8.5   0.0   0.00
507  25.9  41   3.6   0.0   0.00
508  25.9  41   3.6   0.0   0.00
509  21.1  71   7.6   1.4   2.17
510  18.2  62   5.4   0.0   0.43
511  27.8  35   2.7   0.0   0.00
512  27.8  32   2.7   0.0   6.44
513  21.9  71   5.8   0.0  54.29
514  21.2  70   6.7   0.0  11.16
515  25.6  42   4.0   0.0   0.00
516  11.8  31   4.5   0.0   0.00

[517 rows x 5 columns]

In [9]:
correlation=df.corr('pearson')#pearson gives linear correlation-when u increase 1 unit of feature and how does it respond
correlation#below is correlation matrix

temp        RH      wind      rain      area
temp  1.000000 -0.527390 -0.227116  0.069491  0.097844
RH   -0.527390  1.000000  0.069410  0.099751 -0.075519
wind -0.227116  0.069410  1.000000  0.061119  0.012317
rain  0.069491  0.099751  0.061119  1.000000 -0.007366
area  0.097844 -0.075519  0.012317 -0.007366  1.000000

In [10]:
X=np.array([df['temp'],df['RH'],df['wind'],df['rain']])
Y=np.array(df['area'])

In [11]:
from sklearn.preprocessing import MinMaxScaler

In [12]:
scaler=MinMaxScaler()

In [13]:
X=np.transpose(X)
Y=Y.reshape(-1,1)
print(X.shape)
print(Y.shape)

(517, 4)
(517, 1)


In [14]:

x=scaler.fit_transform(X)
y=scaler.fit_transform(Y)

In [15]:
#plt.plot(x,y,'r.')

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
regressor=LinearRegression()

In [19]:
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [20]:
y_pred=regressor.predict(x_test)

In [21]:
y_pred

array([[ 0.01376482],
       [ 0.01740034],
       [ 0.01438824],
       [ 0.02256621],
       [ 0.01179043],
       [ 0.00980601],
       [ 0.00339856],
       [ 0.01785323],
       [ 0.01086208],
       [ 0.01103983],
       [ 0.0175836 ],
       [ 0.01519706],
       [ 0.00915629],
       [ 0.01698883],
       [ 0.00972561],
       [ 0.01215045],
       [ 0.01840879],
       [ 0.01079252],
       [ 0.00503534],
       [ 0.01932237],
       [ 0.02278702],
       [ 0.02310881],
       [ 0.01268264],
       [ 0.01262611],
       [ 0.01931522],
       [ 0.01636813],
       [ 0.00826204],
       [-0.0014351 ],
       [-0.00910165],
       [ 0.00405415],
       [ 0.00977384],
       [ 0.00094633],
       [ 0.00968012],
       [ 0.02592224],
       [ 0.01087724],
       [ 0.02601511],
       [ 0.00570058],
       [ 0.00308338],
       [ 0.02505847],
       [ 0.02324846],
       [ 0.01227355],
       [ 0.01257292],
       [ 0.01844418],
       [ 0.01273146],
       [ 0.01212916],
       [ 0

In [22]:
for i in zip(y_pred,y_test):
    print(i)

(array([0.01376482]), array([0.02584247]))
(array([0.01740034]), array([0.]))
(array([0.01438824]), array([0.00517949]))
(array([0.02256621]), array([0.0005592]))
(array([0.01179043]), array([0.]))
(array([0.00980601]), array([0.]))
(array([0.00339856]), array([0.0004767]))
(array([0.01785323]), array([0.]))
(array([0.01086208]), array([0.]))
(array([0.01103983]), array([0.00134759]))
(array([0.0175836]), array([0.]))
(array([0.01519706]), array([0.]))
(array([0.00915629]), array([0.00645374]))
(array([0.01698883]), array([0.]))
(array([0.00972561]), array([0.]))
(array([0.01215045]), array([0.03527557]))
(array([0.01840879]), array([0.00583037]))
(array([0.01079252]), array([0.00065087]))
(array([0.00503534]), array([0.]))
(array([0.01932237]), array([0.]))
(array([0.02278702]), array([0.00590371]))
(array([0.02310881]), array([0.]))
(array([0.01268264]), array([0.00660959]))
(array([0.01262611]), array([0.]))
(array([0.01931522]), array([0.]))
(array([0.01636813]), array([0.25533534]

In [23]:
from sklearn.metrics import mean_squared_error,r2_score

In [24]:
mean_squared_error(y_test,y_pred)

0.0011635075165259729

In [27]:
r2_score(y_test,y_pred)#tells the best possible fit:percentage of points to be fitted

-0.047437586018889366